POST http://localhost:3003/user/create
Content-Type: application/json

{
    "name": "teste",
    "email": "email@email.com",
    "password": "23432535"
}

### Exercício 1 - Get users
GET http://localhost:3003/user/allUsers

### Exercicio 3 - Create Movie
POST http://localhost:3003/movie
Content-Type: application/json

{
    "title": "Harry Potter",
    "description": "Pequeno bruxo em hogwarts",
    "duration_in_minutes": 320,
    "year_of_release": 2005
}

