POST http://localhost:3003/user/create
Content-Type: application/json

{
    "name": "Jhonatta",
    "email": "jhonatta@email.com",
    "password": "123456"
}

### Exercício 1 - Get users
GET http://localhost:3003/user/allUsers

### Exercicio 3 - Create Movie
POST http://localhost:3003/movie/createMovie
Content-Type: application/json

{
    "title": "A Dama e o Vagabundo",
    "description": "Dois cães apaixonados que gostam de espaguete!",
    "duration_in_minutes": 250,
    "year_of_release": 1998
}

